title: m09's
email: mog@crydee.eu
description: "m09's personal website."
baseurl: ""
url: "https://crydee.eu"
github_username:  m09

markdown: kramdown
theme: minima
permalink: pretty
show_excerpts: True
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
